import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Must come last so it can disable any stylistic rules above that would
  // conflict with Prettier's formatting.
  eslintConfigPrettier,
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma-generated client (regenerated by `prisma generate`).
    "src/generated/**",
    // Playwright output — HTML reports embed a large minified bundle and
    // trace/test-results carry generated JS/JSON. Gitignored already; ESLint's
    // flat config does not read .gitignore, so it needs its own entry or a
    // local Playwright run buries real findings under thousands of warnings.
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
  ]),
]);

export default eslintConfig;
