import { getTranslations } from "next-intl/server";

import type { FeeBalanceView } from "@/modules/fees";

import {
  cancelChargeAction,
  recordPaymentAction,
  waiveChargeAction,
} from "./actions";
import { formatCalendarDate, formatMoney } from "./format";

/**
 * One balance view, rendered — shared by BOTH sections
 * `src/app/people/[personId]/page.tsx` embeds ("as payer" and "as student").
 * `15-…` §6.1's own screen, R-32's own requirement: open charges, recorded
 * payments and a running balance, per payer and per student — never a
 * separate route (see `src/app/fees/actions.ts`'s `backPath` comment for
 * why: resolving a `Charge.studentProfileId` back to the CHILD's own
 * `Person` id, to link a dedicated student page, has no published service
 * to call — the person screen already has both ids in scope, so the view
 * lives there instead of inventing one).
 *
 * `state` renders as the badge; `status` (the STORED value) never does —
 * `domain/balance.ts`'s own point, made visible: what a person reads here is
 * always the derived figure, never a cache.
 */
export async function FeeBalanceSection({
  headingKey,
  backPath,
  balance,
  clientEventIdFor,
}: {
  headingKey: "asPayer" | "asStudent";
  backPath: string;
  balance: FeeBalanceView;
  /** A fresh id per row, for `Payment.clientEventId` (P-02) — generated by
   * the caller so every render of this component gets distinct ones without
   * this file importing `node:crypto` per charge itself. */
  clientEventIdFor: (chargeId: string) => string;
}) {
  const t = await getTranslations();

  return (
    <section className="mt-5">
      <h2 className="h4">{t(`fees.balance.${headingKey}`)}</h2>

      {balance.charges.length === 0 ? (
        <p className="text-muted">{t("fees.balance.empty")}</p>
      ) : (
        <>
          <table className="table table-sm align-middle">
            <thead>
              <tr>
                <th scope="col">{t("fees.balance.columns.feeType")}</th>
                <th scope="col">{t("fees.balance.columns.period")}</th>
                <th scope="col">{t("fees.balance.columns.dueDate")}</th>
                <th scope="col">{t("fees.balance.columns.amount")}</th>
                <th scope="col">{t("fees.balance.columns.paid")}</th>
                <th scope="col">{t("fees.balance.columns.open")}</th>
                <th scope="col">{t("fees.balance.columns.status")}</th>
                <th scope="col">
                  <span className="visually-hidden">
                    {t("fees.balance.actions")}
                  </span>
                </th>
              </tr>
            </thead>
            <tbody>
              {balance.charges.map((charge) => (
                <tr key={charge.id}>
                  <td>
                    {charge.feeTypeName}
                    {charge.note ? (
                      <div className="form-text mb-0">{charge.note}</div>
                    ) : null}
                  </td>
                  <td>
                    {charge.periodStart
                      ? formatCalendarDate(charge.periodStart)
                      : "—"}
                    {charge.periodEnd
                      ? ` – ${formatCalendarDate(charge.periodEnd)}`
                      : ""}
                  </td>
                  <td>{formatCalendarDate(charge.dueDate)}</td>
                  <td>{formatMoney(charge.amount, charge.currency)}</td>
                  <td>
                    {formatMoney(charge.balance.paidAmount, charge.currency)}
                  </td>
                  <td>
                    {formatMoney(charge.balance.openAmount, charge.currency)}
                  </td>
                  <td>
                    <span
                      className={`badge text-bg-${badgeClass(charge.balance.state)}`}
                    >
                      {t(`fees.balance.states.${charge.balance.state}`)}
                    </span>
                  </td>
                  <td>
                    {charge.payments.length > 0 ? (
                      <details>
                        <summary className="small">
                          {t("fees.balance.payments", {
                            count: charge.payments.length,
                          })}
                        </summary>
                        <ul className="list-unstyled small mb-0">
                          {charge.payments.map((payment) => (
                            <li key={payment.id}>
                              {formatCalendarDate(payment.receivedAt)} —{" "}
                              {formatMoney(payment.amount, charge.currency)} (
                              {t(
                                `fees.balance.methods.${payment.method}` as "fees.balance.methods.CASH",
                              )}
                              {payment.reference
                                ? ` — ${payment.reference}`
                                : ""}
                              )
                            </li>
                          ))}
                        </ul>
                      </details>
                    ) : null}
                    {charge.status === "OPEN" ? (
                      <details className="mt-1">
                        <summary className="small">
                          {t("fees.balance.actionsToggle")}
                        </summary>
                        <form
                          action={recordPaymentAction}
                          className="row g-1 mt-1"
                        >
                          <input
                            type="hidden"
                            name="chargeId"
                            value={charge.id}
                          />
                          <input type="hidden" name="back" value={backPath} />
                          <input
                            type="hidden"
                            name="clientEventId"
                            value={clientEventIdFor(`${charge.id}_pay`)}
                          />
                          <div className="col-auto">
                            <input
                              className="form-control form-control-sm"
                              type="number"
                              min="0.01"
                              step="0.01"
                              name="amount"
                              placeholder={t("fees.balance.form.amount")}
                              style={{ width: "6rem" }}
                              required
                            />
                          </div>
                          <div className="col-auto">
                            <select
                              className="form-select form-select-sm"
                              name="method"
                              defaultValue="BANK"
                            >
                              <option value="BANK">
                                {t("fees.balance.methods.BANK")}
                              </option>
                              <option value="CASH">
                                {t("fees.balance.methods.CASH")}
                              </option>
                              <option value="OTHER">
                                {t("fees.balance.methods.OTHER")}
                              </option>
                            </select>
                          </div>
                          <div className="col-auto">
                            <input
                              className="form-control form-control-sm"
                              type="text"
                              name="reference"
                              placeholder={t("fees.balance.form.reference")}
                              maxLength={1000}
                              style={{ width: "8rem" }}
                            />
                          </div>
                          <div className="col-auto">
                            <button
                              type="submit"
                              className="btn btn-sm btn-outline-primary"
                            >
                              {t("fees.balance.form.recordPayment")}
                            </button>
                          </div>
                        </form>

                        <form
                          action={waiveChargeAction}
                          className="row g-1 mt-1"
                        >
                          <input
                            type="hidden"
                            name="chargeId"
                            value={charge.id}
                          />
                          <input type="hidden" name="back" value={backPath} />
                          <div className="col-auto">
                            <input
                              className="form-control form-control-sm"
                              type="text"
                              name="reason"
                              placeholder={t(
                                "fees.balance.form.reasonPlaceholder",
                              )}
                              maxLength={500}
                              required
                              style={{ width: "10rem" }}
                            />
                          </div>
                          <div className="col-auto">
                            <button
                              type="submit"
                              className="btn btn-sm btn-outline-secondary"
                            >
                              {t("fees.balance.form.waive")}
                            </button>
                          </div>
                        </form>

                        <form
                          action={cancelChargeAction}
                          className="row g-1 mt-1"
                        >
                          <input
                            type="hidden"
                            name="chargeId"
                            value={charge.id}
                          />
                          <input type="hidden" name="back" value={backPath} />
                          <div className="col-auto">
                            <input
                              className="form-control form-control-sm"
                              type="text"
                              name="reason"
                              placeholder={t(
                                "fees.balance.form.reasonPlaceholder",
                              )}
                              maxLength={500}
                              required
                              style={{ width: "10rem" }}
                            />
                          </div>
                          <div className="col-auto">
                            <button
                              type="submit"
                              className="btn btn-sm btn-outline-danger"
                            >
                              {t("fees.balance.form.cancel")}
                            </button>
                          </div>
                        </form>
                      </details>
                    ) : null}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="fw-semibold">
            {t("fees.balance.total")}{" "}
            {formatMoney(balance.totalOpenAmount, balance.currency ?? "EUR")}
          </p>
        </>
      )}
    </section>
  );
}

function badgeClass(
  state: FeeBalanceView["charges"][number]["balance"]["state"],
): string {
  switch (state) {
    case "OPEN":
      return "warning";
    case "PARTIAL":
      return "info";
    case "PAID":
      return "success";
    case "WAIVED":
    case "CANCELLED":
      return "secondary";
  }
}
